name: 'test'
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: install requirements
            run: pip install -r requirements.txt
          - name: RUN TEST
            run: python -m pytest tests/*.py
