name: 'testing...'
on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: LS
            run: ls
          - name: install requirements
            run: pip -r install requirements.txt
